### ISSUE TITLE
Recomendaciones de mejora

### ISSUE THREAD

**Issue by gaposx** [DanellySotomayor/lim-2018-05-bc-core-am-cipher#1]
**HTML**
* Te sugerimos usar más etiquetas semánticas como `<header>`, `<section>`.
* Para seguir buenas prácticas, te sugerimos definir los `id` y `clases` de elementos en minúsculas y separados por guiones (-).

**JS**
* Siempre es recomendable almacenar las referencias a elementos del DOM en constantes para que puedan ser utilizadas en otras partes del código.
* Recuerda que uno de los requerimientos del proyecto era estar implementado completamente en ES6, esto incluye los loops (`for`).
* Para proyectos futuros, te sugerimos seguir la [guía de estilos de Laboratoria sobre JS](https://github.com/Laboratoria/js-style-guide).

**CSS**
* Recuerda usar clases descriptivas y en inglés.

**TESTS**
* Esta parte era requerida y no fue implementada. Te sugerimos para los siguientes proyectos que desarrolles con orientación a las pruebas.

Buen trabajo!

**Comment by DanellySotomayor** [comment]
Hola @gaposx ,

Gracias por las recomendaciones, las voy a tener en cuenta para los próximos proyectos. Te comento que por error no subí el Test Cipher, el cual si había implementado para la fecha de presentación del proyecto. No me di cuenta que no se había subido hasta ahora, mil disculpas, voy a tener más cuidado con eso en próximos proyectos.

Gracias Gonzalo!!
